M48
; DRILL file {KiCad (7.0.0)} date Tue May  9 15:07:42 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-09T15:07:42+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.702
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.905
%
G90
G05
T1
X97.699Y-52.5
T2
X102.199Y-52.5
T0
M30
